services:
  fresnel:
    build:
      context: .
      dockerfile: fresnel.Dockerfile
      args:
        - FRESNEL_USER_ID=$FRESNEL_USER_ID
        - FRESNEL_TIMEZONE=$FRESNEL_TIMEZONE
        - INSTALL_X_TOOLS=${INSTALL_X_TOOLS:-false}
    hostname: fresnel
    user: dev
    working_dir: /home/dev
    network_mode: bridge
    environment:
      - USER=dev
      - HOST_USER=$USER
      - TERM
      - GIT_CEILING_DIRECTORIES=/va:/home/dev
      - DISPLAY=host.docker.internal:0
    privileged: true
    ports:
      - "2222:22"   # SSH
      - "2002:2002" # HTTP proxy over socks tunnel
      - "8000:8000" # Remote debugging
      - "8040:8040" # mpi-fhir-query
      - "8050:8050" # charon
      - "8070:8070" # cerner-fhir-query
      - "8090:8090" # data-query
      - "8095:8095" # vista-fhir-query
      - "8888:8888" # yanartas
      - "9090:9090" # mock-mpi
      - "9001:9001" # whatever
      - "9002:9002" # whatever
      - "9003:9003" # whatever
    volumes:
      - .:/fresnel-dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $FRESNEL_EXCHANGE_DIR:/var/run/fresnel
      - $HOME/.fresnel/home:/home/dev
      - $HOME/.m2/repository:/repository
      - $FRESNEL_GITHUB_REPO_DIR:/va
      - $HOME/Downloads:/Downloads
