#!/usr/bin/env bash
set -euo pipefail
if [ "${DEBUG:-false}" != false ]; then set -x; fi
cd $(dirname $0)
. fresnel.env

determineTimezone() {
  # Guess which timezone
  if [ "${FRESNEL_TIMEZONE:-automatic}" == automatic ]
  then
    local target=$(/usr/bin/readlink /etc/localtime)
    if [ -n "${target:-}" ]
    then
      export FRESNEL_TIMEZONE=$(echo $target | cut -d "'" -f 4 | sed 's/.*zoneinfo\///')
    fi
  fi
}


doSomethingWithX11() {
  if /usr/bin/which xhost > /dev/null 2>&1
  then
    export INSTALL_X_TOOLS=true
    echo "X11 tools will be installed in Fresnel."
  fi
}

startFresnelSshd() {
  echo "Starting Fresnel sshd"
  ./fresnel-host/bin/fresnel-sshd
}

determineTimezone
doSomethingWithX11
startFresnelSshd

docker compose build $@
docker compose up --detach --force-recreate

