#!/bin/sh
set -euo pipefail

cd $(dirname $0)
HERE=$(pwd)
cd ..
. fresnel.env

PLIST=~/Library/LaunchAgents/fresnel.exchange.plist

cat > $PLIST <<EOF
<?xml version=“1.0” encoding=“UTF-8”?>
<!DOCTYPE plist PUBLIC “-//Apple//DTD PLIST 1.0//EN” “http://www.apple.com/DTDs/PropertyList-1.0.dtd”>
<plist version=“1.0”>
  <dict>
    <key>Label</key>
    <string>fresnel.exchange</string>
    <key>ProgramArguments</key>
    <array>
      <string>$HERE/fresnel-exchange-handler</string>
    </array>
    <key>WatchPaths</key>
    <array>
      <string>$FRESNEL_EXCHANGE_DIR/in</string>
    </array>
  </dict>
</plist>
EOF

cat $PLIST

$HERE/uninstall
echo "Loading fresnel.exchange ($PLIST)"
launchctl load $PLIST
